name: kkpy
channels:
- conda-forge
dependencies:
- numpy
- pandas
- scipy
- matplotlib
- dask
- netcdf4
- cartopy
- arm_pyart
- xarray
- geopandas
- descartes
- bottleneck
- scikit-image
- astropy
- parse
- numba
- pip
- pip:
  - haversine
